### PR TITLE
clean up html style and formatting

### PR DESCRIPTION
**Pull request by mike-keogh**
I formatted and styled the html accordingly. Please check for anything I may have missed.

### CODE REVIEW

**Comment by AnnahGerletti** [comment]
all good

**Comment by mike-keogh** [comment]
!!!

**Comment by aaron-macdonald** [comment]
Hey Mike, Line 99 there is a <p> tag on the same line as the text ... unacceptable !!!

Other than that looks great :)

**Comment by mike-keogh** [comment]
Are you sure its line 99? Looks clean to me lol? Hows yours going?

**Pull request closed without merging**
